### ISSUE TITLE
Doesn't install the latest mono

### ISSUE THREAD

**Issue by jimmyface** [linuxhq/ansible-role-jackett#1]
This role worked great in installing Jackett for me; however, when I log in I get a nasty message " A minimum Mono version of 5.8 is required. Please update to the latest version from http://www.mono-project.com/download/"
It looks like this role installs an older version of mono which generates this message. Can this be updated to use mono 5.8 or better?

**Comment by tkimball83** [comment]
I created an ansible role for mono as well to tackle this issue as the epel version is dated, but I didn't want to force a dependency in the role in case users wanted to get their mono packages via other means.  Take a look at the following repository.

https://github.com/linuxhq/ansible-role-mono

With that said, they recently released 5.14 to their repository which doesn't play nicely with jackett.  I'd recommend version locking to the latest 5.12 release which hasn't caused me any issues, see the version below.

```
$ rpm -q mono-core
mono-core-5.12.0.301-0.xamarin.1.epel7.x86_64
```

The mono role currently doesn't support adding excludes to the repository configuration.  If you end up using that role and want me to add support for excludes open an issue under that repository and I'll get that fixed up for you.

**Comment by jimmyface** [comment]
Great, thank you. I'll check that role out. In the meantime for this role, is it possible to have it check the mono version and warn if it's too old? I love that this whole thing sets up Jackett but that big red warning is a real buzzkill.

**Comment by tkimball83** [comment]
I suppose we could have it check the mono version after jackett is installed, and then skip the remaining tasks if the result is less than 5.8 (or just the service start/enabling task).

Unfortunately we can't check the mono version prior to the jackett installation as yum may pull in the mono dependencies as apart of the install, depending on the end users configuration.

I can also update the requirements section of the README to include this information and link to the mono role I put together.

Thoughts?

**Comment by jimmyface** [comment]
I like that idea. Updating the README as well as perhaps putting some sort of notice / warning in the role itself would cover both bases.

**Comment by tkimball83** [comment]
Please take a look at tag/version 0.2 and let me know if that'll suffice?

Thanks!

**Comment by tkimball83** [comment]
I'm going to close this issue.  Please re-open if you need additional changes made.

Thanks!
